### ISSUE TITLE
[Feature] 2.0 TO-DO Changes

### ISSUE THREAD

**Issue by Voltstro** [Voltstro/VoltProjects#112]
This issue tracks what needs to be done in VP 2.0.

(I been very bad and haven't included everything that has been done to VP 2.0 in this issue, since the scope has changed so much, and only now has been pretty much set.)

---

## Builder

- [x] Manage Git Repos
- [x] Execute Pre-Build Commands
- [x] Pre-Build Commands Order
- [x] Description Extraction
- [x] Assets Handling
- [x] Improve upsert commands generation
- [x] Check repo Git hashes

## Server/Client
- [x] Git Repo BTN in top right corner
- [ ] Open Current Doc in Git
- [x] Better redirections
- [x] Better Error Page
- [ ] Breadcrumbs
- [x] Sitemap.xml
- [x] Caching of Project Menu and TOCs
- [x] FiraCode Monospace Font (I like it)

## Database
- [x] Pre-Build Commands Order
- [ ] Breadcrumbs
- [x] Use more 'postgres' naming style

**Comment by Voltstro** [comment]
Remaining tasks will be moved to the TO-DO of the next major release.
