### ISSUE TITLE
[Feature] 2.1 TO-DO Changes

### ISSUE THREAD

**Issue by Voltstro** [Voltstro/VoltProjects#153]
Stuff that will hopefully be done for 2.1.

---

## Builder

- [x] Support for docfx 2.0
- [x] Tracing 
- [x] Pages track what pages are using what storage items
- [x] Support for "External Items"
- [x] Current page's git link

## Server

- [x] TOC Improvements
- [x] Re-redirects for "External Items"
- [x] Metabar
- [x] Open current page in git
- [x] (Possibly) Share page button

## Database

- [x] DB timestamps
- [x] `upsert_project_pages` does not update all properties on update

**Comment by Voltstro** [comment]
Release 2.1.0 done.
