### ISSUE TITLE
Docs Search

### ISSUE THREAD

**Issue by Voltstro** [Voltstro/VoltProjects#181]
## Docs Search

The ability to search across doc pages. Currently you can only search across articles via the TOC's search, which searches across the current TOC page titles on the client side.

We want the ability to search docs, both via it's title and content. Postgres has good full text searching, which also handles our `content` field holding HTML content very well. It also means not running/using an external service for search.
Text-Search types in postgres need a `regconfig` value, containing a configuration for a language. While VP doesn't have proper support for multi-language, we still want to keep `project_pages` multi-lang, to not make future life harder. The index that is needed for good performance TS in postgres can pull it's config from a column. We can't use subqueries in indexes, so a column will need to be added to `project_pages`.

### Tasks

- [ ] Add `language_config` of type `regconfig` to `project_pages`. This value shall be provided by a new column in `language` called `configuration`.
- [ ] Add new index to `project_pages` for search vector
   ```sql
  CREATE INDEX ix_project_page_search_vector ON public.project_page USING gin (to_tsvector(language_config, content));
  ```
- [ ] UI - To be designed still
